spring:
  application:
    name: api-gateway

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://localhost:8888
      username: ${CONFIG_USERNAME:config}
      password: ${CONFIG_PASSWORD:password}
